<<<<<<< HEAD
import React, { useState } from 'react';

import VideoSection from './components/VideoSection';
import FeaturesSection from './components/Features';
import Testimonials from './components/Testimonials';
import CTA from './components/CTA';
import Pricing from './components/Pricing';
import Header from './components/Header';
import Footer from './components/Footer';
import Hero from './components/Hero'
import GoToTop from './components/GoToTop';
import '../../App.css'


// Main Component
const LandingPage = () => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  return (
    <div className="min-h-screen text-white overflow-hidden">
      {/* Header */}
      <Header />

      {/* Hero Section */}
     <Hero/>

      {/* Video Section */}
      <VideoSection />

      {/* Features Section */}
      <FeaturesSection />

      {/* Testimonials Section */}
      <section id="testimonials" className="py-20">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-5xl md:text-6xl font-bold mb-12">
            Our Clients'
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-blue-500 to-purple-500">
              Voices
            </span>
          </h2>
          <p className="text-lg text-gray-300  max-w-5xl mx-auto mb-8">
            This testimonials section you are seeing here is also a widget generated by{' '}
            <span className='font-bold text-xl'>
              Clients
              <span className="bg-clip-text text-transparent bg-gradient-to-r from-blue-500 to-purple-500">
                Voice
              </span>
            </span>
            . It's an actual <b>"Wall of Love"</b> with a <b>horizontal layout and auto-scrolling enabled</b> to keep the positive feedback flowing!
          </p>
          <Testimonials />
        </div>
      </section>

      {/* Call to Action Section */}
      <CTA />

      {/* Pricing Section */}
      <Pricing />
      <GoToTop/>
      {/* Footer */}
      <Footer />
    </div>
  );
};

=======
import React from "react";
import ReactDOM from "react-dom/client";
import Header, {Hero} from "./components/Header";
import Testimonials from "./components/Testimonials";
import Features from "./components/Features";
import CTA from "./components/CTA";
import Footer from "./components/Footer";
import './style.css'


const LandingPage=()=>{
    return (<>
        <Header/>
        <Hero/>
        <Testimonials/>
        <Features/>
        <CTA/>
        <Footer/>
    </>);
}
>>>>>>> edd34ec68b5f8db24eae3d7f1074077213774225
export default LandingPage;
