export const BUSINESS_CATEGORIES = [
    { value: "accounting", label: "Accounting" },
    { value: "advertising", label: "Advertising" },
    { value: "agriculture", label: "Agriculture" },
    { value: "construction", label: "Construction" },
    { value: "education", label: "Education" },
    { value: "finance", label: "Finance" },
    { value: "healthcare", label: "Healthcare" },
    { value: "hospitality", label: "Hospitality" },
    { value: "information_technology", label: "Information Technology" },
    { value: "insurance", label: "Insurance" },
    { value: "legal_services", label: "Legal Services" },
    { value: "manufacturing", label: "Manufacturing" },
    { value: "marketing", label: "Marketing" },
    { value: "media", label: "Media" },
    { value: "nonprofit", label: "Nonprofit" },
    { value: "real_estate", label: "Real Estate" },
    { value: "retail", label: "Retail" },
    { value: "shipping", label: "Shipping and Logistics" },
    { value: "social_media", label: "Social Media" },
    { value: "technology", label: "Technology" },
    { value: "tourism", label: "Tourism" },
  ];